### PR TITLE
Improve usability in scripts, CI and as a library

### PR DESCRIPTION
**Pull request by nazarewk**
## Description

This PR helps with using `gimme-aws-creds` in scripting and as a library:

- allows listing all available roles (by arn) with `--action-list-roles`
- fixes y/n default entries for configuration updates
- adds `json` output format (the default is called `bash` now)
- adds role as a comment in `bash` output
- standarize on CLIUserInterface: print to `stderr` instead of `stdout` #96
- enables selecting multiple roles with `--roles`
- enables CSV and regexp in `aws_rolename` config and `--roles` flag
- prefixes `--action-` in front of all action configurations (preserving old syntax)
- allows storing `~/.aws/credentials` from previous command's output, input can be fed
  from `json` format, eg: `gimme-aws-creds -o json --roles '/123456789012/' | gimme-aws-creds --action-store-json-creds`

## Related Issue

- https://github.com/Nike-Inc/gimme-aws-creds/issues/86
- https://github.com/Nike-Inc/gimme-aws-creds/issues/96
- https://github.com/Nike-Inc/gimme-aws-creds/issues/120

## Motivation and Context

I am working on integrating `gimme-aws-creds` in scripts and basic library usage.

## How Has This Been Tested?

- minimal additions to test, in future could be tested using `UserInterface`.
- running commands manually
- using as a library in a project

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change) - depends whether we consider internal non-CLI code restructuring as breaking changes

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by nazarewk** [comment]
Updating documentation and should be ready for merging soon

**Comment by nazarewk** [comment]
PR is ready for review

**Comment by Sector95** [comment]
We'll get a review going, thanks!

**Comment by Sector95** [comment]
Thanks!

**Comment by cturner-confluent** [comment]
Hey @nazarewk do you have any examples of how you are using this in scripts as part of CI?

**Comment by nazarewk** [comment]
@cturner-confluent I have not been working with AWS for almost a year.
From what I see there is an example in [README.md](https://github.com/Nike-Inc/gimme-aws-creds/blob/9fd4c4835315413b3104be601ac7e16b81bd0715/README.md#usage-in-python-code) and reference implementation of the UI in [gimme_aws_creds/ui.py](https://github.com/Nike-Inc/gimme-aws-creds/blob/9fd4c4835315413b3104be601ac7e16b81bd0715/gimme_aws_creds/ui.py#L102-L118) (it's quite simple if you wanted different interactions than CLI)

**Comment by cturner-confluent** [comment]
@nazarewk thanks for the reply I will try and piece something together, thanks!

**Pull request merged**
