### PR TITLE
Fix localhost redirect

### PR DESCRIPTION
**Pull request by ChristophShyper**
As proposed by @iniquityx2  here https://github.com/Nike-Inc/gimme-aws-creds/issues/302

## Description

As in title.

## Related Issue

https://github.com/Nike-Inc/gimme-aws-creds/issues/302
https://github.com/Nike-Inc/gimme-aws-creds/issues/44

## Motivation and Context

My whole company cannot work today. And probably not only mine..

## How Has This Been Tested?

Yes. Tested it locally and it works.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by goshiz** [comment]
Our IT dept tested this fix and it's working.

**Comment by ChristophShyper** [comment]
@bwynsm @Sector95 Can you have a look? This is very urgent and high severity issue for many companies.

Some people are also reporting issues with `Extra Verification` in SAML response (https://github.com/Nike-Inc/gimme-aws-creds/issues/302#issuecomment-870428653).

**Comment by brysontyrrell** [comment]
Our staff have been implementing this fix as well and it is working.

**Review by bwynsm — APPROVED** [review]

**Comment by danwalker47** [comment]
Hello.  Small FYI:  The version tag v2.4.2 isn't matching what is in the __init__.py file as 2.4.1.

**Pull request merged**
