### PR TITLE
Preserve case-sensivity in cred_profile name

### PR DESCRIPTION
**Pull request by angystardust**
`gimme_aws_creds` should preserve case-sensivity in _cred_profile_ name

## Description

We need to preserve case-sensitivity if we specify a custom `cred_profile` name and the custom name isn't equal to one of the 3 managed options: '_default_', '_role_',  '_acc-role_'.
This patch is required in case we're reading the configuration from an existing `gimme_aws_creds` profile 
 
## Motivation and Context

This fix case insensivity in cred_profile name in case we read it from a config file.
This small patch makes gimme_aws_creds coherent between interactive cli usage and when it reads the configuration from a config file.

## How Has This Been Tested?

Small change, I have tested it locally.
Create a config profile with the following parameter:
```
write_aws_creds = True
cred_profile = TeStMe123
```

launch `gimme_aws_creds` using the custom profile and check for the aws profile name in _~/.aws/credentials_ 
The case-sensivity of the aws profile name should be preserved.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Sector95** [comment]
This broke the tests.  Also, where does the change in casing come between that dictionary, and the passed-in value?  Seems odd.

**Comment by angystardust** [comment]
Hi @Sector95 thanks for your reply. I cannot see why the tests are broken. 
Can you please guide me to improve/fix the patch?

**Comment by Sector95** [comment]
Hi @angystardust, on your local machine you can run `nosetests` in the repository and see which test(s) are failing.  In this case, the change is causing the test to trigger the "first-run configuration" I think:

> testing else statement in get_profile_name ... No gimme-aws-creds configuration file found, starting first-time configuration...
Enter the Okta URL for your organization. This is https://something.okta[preview].com
Okta URL for your organization: 

At which point the test times out because there's no one there to answer it's questions!

**Comment by angystardust** [comment]
Thanks for the explaination @Sector95!
And sorry for the noise. I've opened a new PR #187 which doesn't break the "first-run configuration" and the unit tests.

**Pull request closed without merging**
