### PR TITLE
Friendly error and version

### PR DESCRIPTION
**Pull request by anners**
I added an error is an appname is not found and added --version.

### CODE REVIEW

**Comment by SectorNine50** [comment]
I personally like the idea of displaying a message, and allowing the user to choose from the list of apps.

**Comment by anners** [comment]
We could throw and error and list the apps that are available. My concern with continuing is that the .okta_aws_login_config never gets cleaned up.

**Comment by anners** [comment]
It looks like @epierce has this covered in his PR. We should merge his and I’ll rebase mine.

**Comment by anners** [comment]
This should be rebased with master and ready to go. It’s just adding —version and a few syntax cleanups

**Pull request merged**
