### PR TITLE
Option to remember the MFA device

### PR DESCRIPTION
**Pull request by edubxb**
## Description
According to the documentation, the MFA device could be remembered for a
limited time if user asks for it.

This PR implements it.

+info:

https://developer.okta.com/docs/api/resources/authn#verify-factor

## Related Issue

Solves #109.

## How Has This Been Tested?

I made some tests with my work accounts.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by edubxb** [comment]
Any chance to get this PR merged?

Thanks!

**Comment by padilo** [comment]
Guys, this would be really nice to have.
Any chance to get this soon?

**Comment by joaoqalves** [comment]
+1 to the previous comments. It would improve my workflow a lot!

**Comment by edubxb** [comment]
@Sector95 any chance to merge this PR? Thanks!

**Comment by Sector95** [comment]
Looks good, sorry for the delay, and thanks for the PR!

**Pull request merged**
