### PR TITLE
run aws session sts code asyncronously vastly improving the performance.

### PR DESCRIPTION
**Pull request by eedgar**
- log success to user
- add threads to speedup execution when you have a large number of roles

### CODE REVIEW

**Comment by eedgar** [comment]
This is much faster when you have a large number of roles.  as long as a new session is created in each thread the boto module becomes threadsafe.  See https://stackoverflow.com/questions/52820971/is-boto3-client-thread-safe for more info.

I could see this pr being parameterized and the threading capabilities become optional with the default being the old style.  This pr works for me .. and is meant to get a discussion on speeding up the calls to aws.

**Comment by eedgar** [comment]
@Sector95 Any chance I could get a review on this?  As it stands its working for me and I see a huge performance boost from it.  Just wanted to share the idea with others.

**Comment by Sector95** [comment]
@bwynsm would be a better contact for this, I'm not really involved with the project anymore.

**Comment by aaa-khoa** [comment]
this is great! was trying to find a solution to help with the 5 min sts max limit since I'm pulling a 100+ roles, this cut the time down to less than a minute!

**Review by aaa-khoa — APPROVED** [review]

**Comment by Rooks103** [comment]
@bwynsm Any chance we can get a review / update on how we get this one merged?

**Comment by eedgar** [comment]
@epierce I see you have recently merged code.. can this be merged also?

**Comment by epierce** [comment]
Everything looks good with this - it's working fine for me.  Thanks for the contribution

**Pull request merged**
