### PR TITLE
Add DUO push & passcode Support

### LINKED ISSUE #159: Duo MFA fails to load web page for iframe and gives syntax error
## Expected Behavior

Choosing Duo web as MFA should open a webpage which opens the iframe for sending a push notification for authentication.

## Current Behavior
A browser opens to http://127.0.0.1:65432/duo.html with a failure to connect, and the below is returned (powershell):

Pick a factor:
[0] web: Duo
Selection: 0
Duo required; opening browser...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 262, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 237, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Scripts\gimme-aws-creds.cmd", line 1
    @echo OFF
          ^
SyntaxError: invalid syntax

### LINKED ISSUE #216: DUO logic for "passcode" & "push" broken
DUO supports both "passcode" & "push" but the current logic in gimme-aws-creds is broken.

1. Okta only passes "web" as a supported factor [Ref](https://help.okta.com/en/prod/Content/Topics/Security/Security_Duo.htm) 

2. If "push" is set as a preferred factor it will not trigger duo because[ factortype["push"](https://github.com/Nike-Inc/gimme-aws-creds/blob/master/gimme_aws_creds/okta.py#L816) comes before [provider['duo']](https://github.com/Nike-Inc/gimme-aws-creds/blob/master/gimme_aws_creds/okta.py#L832)

3. If "passcode" is passed and 1 & 2 were fixed then this [code](https://github.com/Nike-Inc/gimme-aws-creds/blob/master/gimme_aws_creds/okta.py#L455-L456) would break because both `fid` and `passcode` are undefined

4. duo passcode should be defaulted to [`self.mfa_code`](https://github.com/Nike-Inc/gimme-aws-creds/blob/master/gimme_aws_creds/okta.py#L455) so that users can pass in `--mfa-code` or set via `OKTA_MFA_CODE`

5. `ret` is not defined and would break if [code](https://github.com/Nike-Inc/gimme-aws-creds/blob/1c8461446b622fc50e209b54c5fdba2d66a5da5f/gimme_aws_creds/okta.py#L494) was run

6. Readme is not up to date with DUO supported methods `web|push|passcode`

7. config is not up to date with DUO Supported methods `web|push|passcode`

## Steps to Reproduce (for bugs)
1. Setup Okta instance that uses DUO for mfa
2. Try setting `passcode` | `push`

## Context
Currently my team can only use the web duo integration, which leaves an open window once service completes, and is not a good user experience

## Your Environment

* App Version used: gimme-aws-creds 2.3.1
* Environment/OS name and version: Darwin LA-C02C8BSJMD6M 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

### PR DESCRIPTION
**Pull request by elijah-roberts**
* Update README
* Update Configure Command
* Add ui/logging to duo Class
* cleanup duo auth logic
* fix broken variable definitions
* Resolves #216

Fix Broken Logic for DUO push|passcode 

### README

1. Update preferred documentation to include duo types including web|push|passcode

### config.py
1. Update ui message for preferred_mfa_type to match README and include descriptions
2. Added DUO types web|push|passcode

### duo.py
1. Added UI/logging to duo class
2. Added logging statement for duo response status
3. Added Error handling for passing a previously used passcode|OTP
4. Fixed sleep logic to only sleep if response status was not successful in order to improve user experience 

### okta.py
1. create default value for `passcode` to fix undefined error.
2. set default value for `passcode` to `self.mfa_code` to leverage  `OKTA_MFA_CODE` | `--mfa_code` functionality
3. fix undefined `id` | `fid` variables by pointing them to factor['id']
4. Add prompt for user to enter pass code if not set via `OKTA_MFA_CODE` | `--mfa_code`
5. created `self._get_response_data` method to make code more DRY
6. Update duo auth status logic to reduce sleeps, and improve user experience
7. Update if statement order in `_login_multi_factor` to ensure that DUO "push" would actually trigger
8. Add in valid duo factors IF duo is the provider, and only `web` is offered.
```
if len(factors) == 1 and factors[0].get('provider') == 'DUO' and factors[0].get('factorType') == 'web':
            push = copy.deepcopy(factors[0])
            push['factorType'] = "push"
            factors.append(push)
            passcode = copy.deepcopy(factors[0])
            passcode['factorType'] = "passcode"
            factors.append(passcode)
```
This is because even though DUO supports these factors, Okta does not provide them as valid factors. This shims them in as valid factors. If Okta in the future provides them as valid factors this if statement will not run because more than 1 factor is returned. 
9. Update the if statement order in `_build_factor_name` to ensure that DUO "push" would be triggered

## Related Issue
Resolves #216 

## Motivation and Context
Currently Duo `push` | `passcode` logic is broken and does not work. Our team would prefer to supply the passcode(OTP), or use the headless push, because the web option opens a browser and does not close.

This could also resolve #159  as workaround to not have to spin up a web browser

## How Has This Been Tested?
I have tested the following:
1. setting `preferred_mfa_type: web` - Worked as expected no regression, window opened and I was able to authenticate. Window did not close
2. setting `preferred_mfa_type: push` - I received a headless duo push ... YAY!
3. setting `preferred_mfa_type: passcode` - I was prompted for a passcode, entered it and successfully authenticated
4. setting `preferred_mfa_type: passcode` & used `OKTA_MFA_CODE` | `--mfa_code to provide the OTP - I was able to authenticate successfully. 
5.  `preferred_mfa_type: passcode` & Used an previously used OTP. - Authentication failed, and I received an error message (via the error handling statement I added) that indicated that I used a old token and needed to try again with a new one
image
6. I set `preferred_mfa_type: None` - I was prompted to choose from three valid options web|passcode|push
image

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes. - Does not look like there is currently a supported method for testing DUO calls via okta.example.com
- [ x] All new and existing tests passed.

### CODE REVIEW

**Comment by elijah-roberts** [comment]
@Sector95  Let me know what you think... I think this might also resolve the issue for #159

**Comment by Sector95** [comment]
Awesome, thank you!

**Comment by battlecow** [comment]
@elijah-roberts is there a specific requirement to use duo push? i get a stack trace and digging into it my return in the `do_auth` method is coming back as html and not json although there is a `sid` hidden form field in there.

**Comment by seb-steuer** [comment]
I'm on gimme-aws-creds 2.3.4 and the only option I'm getting is "web: Duo". Not getting a choice for push or passcode at all. And all 3 methods works for my user when I go to okta website.

**Pull request merged**
